
--creamso la base de datos--
CREATE DATABASE FARMACIA_CURITA;
USE FARMACIA_CURITA;
--cremaos tabla de usuarios
CREATE TABLE USUARIOS(
ID_PERSONA INT IDENTITY (1,1) PRIMARY KEY,--hace autoincrementable el campo
PUESTO VARCHAR(14) NOT NULL,
NOMBRE VARCHAR(28) NOT NULL,
APELLIDO VARCHAR(28) NOT NULL,
EDAD INT NOT NULL,
SEXO VARCHAR(1) NOT NULL,--"m"/"f"--
ROL1 BIT NOT NULL DEFAULT 0,--rol de administrador
ROL2 BIT NOT NULL DEFAULT 0,--rol de administrador
ROL3 BIT NOT NULL DEFAULT 0,--rol de administrador
ROL4 BIT NOT NULL DEFAULT 0,--rol de cajas
ROL5 BIT NOT NULL DEFAULT 0,--rol de cajas
US VARCHAR(28) NOT NULL,--usuario
CONT VARCHAR(15) NOT NULL,--contraseña
ACTIVO BIT NOT NULL DEFAULT 0,--pernitira validar si el usuario puede trabjar
FECHA_CREACION_USUARIOS DATETIME NOT NULL DEFAULT GETDATE()--inserta la fecha del servidor por defecto 
);
select *from USUARIOS;

--creamos tabla de productos
CREATE TABLE PRODUCTO(
ID_PRODUCTO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE_PRODUC VARCHAR(28) NOT NULL,
MARCA_PRODUC VARCHAR(28) NOT NULL,
DESCRIPCION_PRODUCTO VARCHAR(240) NOT NULL,
IMAGEN IMAGE,--siber para almacenar imagene en bits
TIPO_ESTDO_MATERIA VARCHAR(10),--validar si es pasitlla,jarabe o otro
CANTIDAD_PRODUCTO INT NOT NULL,--cantidad de porducto
PRECIO DECIMAL (5,2)NOT NULL,--guarda los valores como 12345.12
PRECIO_TOTAL DECIMAL(8,2)NOT NULL,--guarda el de productos existentes
FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE()
);

--tabla ventas
  
CREATE TABLE VENTAS(
ID_VENTA INT IDENTITY (1,1) PRIMARY KEY,
NUMERO_FACTURA INT NOT NULL,
NOMBRE_PRODUC VARCHAR(28) NOT NULL,
MARCA_PRODUC VARCHAR(28) NOT NULL,
TIPO_ESTDO_MATERIA VARCHAR(10),
CANTIDAD_PRODUCTO INT NOT NULL,
NIT VARCHAR(28) NOT NULL DEFAULT 'Consumidor Final' ,
NOMBRE_FACTURA VARCHAR(28) NOT NULL,
US VARCHAR(28) NOT NULL,
PRECIO DECIMAL (5,2)NOT NULL,
SUB_TOTAL DECIMAL (5,2) NOT NULL,
FECHA_VENTA DATETIME NOT NULL DEFAULT GETDATE()
);


--TABLA PARA FACTURAS
CREATE TABLE FACTURAS(
ID_FACTURA INT IDENTITY (1,1) PRIMARY KEY,
NUMERO_FACTURA INT NOT NULL,
NIT INT NOT NULL,
NOMBRE_FACTURA VARCHAR(28) NOT NULL DEFAULT'Consumidor Final',
TOTAL DECIMAL (5,2) NOT NULL,
US VARCHAR(28) NOT NULL,
FECHA_VENTA DATETIME NOT NULL DEFAULT GETDATE()
);
